[theme]
base="dark"                         # force dark mode
primaryColor="#088561"              # emerald accents
backgroundColor="#c2cdcf"           # deep navy background
secondaryBackgroundColor="#111827"  # cards/side panels
textColor="#e5e7eb"                 # light text
font="sans serif"
