[theme]
base="dark"                         # force dark mode
primaryColor="#d6b627"              # emerald accents
backgroundColor="#464747"           # deep navy background
secondaryBackgroundColor="#111827"  # cards/side panels
textColor="#e5e7eb"                 # light text
font="sans serif"
