[theme]
base="light"                         # force light mode
primaryColor="#d6b627"              # emerald accents
backgroundColor="#f5fcfc"           # deep navy background
secondaryBackgroundColor="#56b09e"  # cards/side panels
textColor="#0a0a0a"                 # light text
font="sans serif"
